### ISSUE TITLE
Crashes when it encounters an empty folder.

### ISSUE THREAD

**Issue by Kiyiko** [kz26/dottorrent-gui#1]

**Comment by lucaslink** [comment]
+1

**Comment by kz26** [comment]
Hi, could you provide the version of dottorrent-gui you're using? The latest version (v1.1.3) should show an error message (and not crash) when encountering an empty directory.

**Comment by Kiyiko** [comment]
I'm on 1.1.3

It does show an error message of "input path must be non-empty" if I make a single torrent of an empty directory, but if I do batch mode and it runs across an empty directory in the process, it either crashes or silently closes.

**Comment by kz26** [comment]
OK, thanks for letting me know. I'll try to have this fixed for the upcoming 1.2.0 release.

**Comment by kz26** [comment]
1.2.0 is now out and should fix this problem.
