### ISSUE TITLE
Is there a command line option?

### ISSUE THREAD

**Issue by xXxBobDolexXx** [kz26/dottorrent-gui#11]
Would like to integrate the program into my workflow, was wondering if there were any command line options

**Comment by kz26** [comment]
Yes, please check out https://github.com/kz26/dottorrent.

**Comment by xXxBobDolexXx** [comment]
When using the gui, after creating a torrent, I have left the comment section blank but it inserts that the torrent was created with dotorrent. Is there any way to prevent this?

**Comment by kz26** [comment]
The comment field is separate from the creator field. It is not possible to override the creator field in either dottorrent-gui or the dottorrent CLI. If you have a special need to change the creator field, you can use the lower-level dottorrent library, which does allow it to be set to a custom value.

**Comment by xXxBobDolexXx** [comment]
I see, looks like I mixed up the creator field and comment field when the client was half minimized, thanks
