### ISSUE TITLE
Error Installing on Linux

### ISSUE THREAD

**Issue by Goodolandy** [kz26/dottorrent-gui#13]
Hello,
Looking forward to trying our your program but when I run the command `pip install dottorrent-gui` I receive the following red coloured error message:

> Could not find a version that satisfies the requirement PyQt5>=5.7 (from dottorrent-gui) (from versions: )
No matching distribution found for PyQt5>=5.7 (from dottorrent-gui)

Any ideas?  I am using the latest Ubuntu Mate 17.04.
Thanks.

**Comment by kz26** [comment]
Hi, what version of Python are you using? PyQt5 only supports Python 3+ - you may need to run `pip3` instead of `pip`.

**Comment by Goodolandy** [comment]
Python 3.5.3-1

**Comment by kz26** [comment]
If pip/pip3 doesn't work, you can also try installing PyQt5 from the Ubuntu repository. I believe the package name is `python3-pyqt5`

**Comment by Goodolandy** [comment]
I tried pip3 and received a message to install python3-pip which I did.  Ran pip3 install dottorrent-gui and it installed but using the command pip3 dottorrent-gui results in unknown command.
