### ISSUE TITLE
dottorrent-gui 1.3.4 does not set the "announce" key in the resulting .torrent file

### ISSUE THREAD

**Issue by thedarkness000** [kz26/dottorrent-gui#15]
When creating torrents using dottorrent-gui 1.3.4, the "announce-list" key is set correctly, but the ["announce"](https://en.wikipedia.org/wiki/Torrent_file#File_structure) [key](https://wiki.theory.org/index.php/BitTorrentSpecification#Metainfo_File_Structure), which should contain the primary tracker's announce URL, is not.  This causes the resulting .torrent file to not be accepted by trackers that validate this parameter.

For example, this is how a torrent generated by dottorrent-gui normally looks (in [BEncode Editor](https://sites.google.com/site/ultimasites/bencode-editor)):
![dottorrent-gui version](https://i.imgur.com/mOYOBHE.png)

And this is how it looks with the "announce" key correctly added:
![fixed version](https://i.imgur.com/KfEsMAu.png)

As you can see, the primary tracker is set as the value for the "announce" key, and is also included in the full list of trackers under the "announce-list".

Can you update dottorrent-gui to add this key to the generated torrent file?  How you handle this in the GUI is up to you, but I think it would be pretty safe to assume that the first tracker entered by the user is the primary.

Thanks!

**Comment by kz26** [comment]
Thanks for the bug report. I'll try to have this fixed in the next release.

**Comment by kz26** [comment]
Fixed in dottorrent-gui v1.3.5 and dottorrent v1.9.2.
