### ISSUE TITLE
"Paste from clipboard" does not work when the path on the clipboard is quoted

### ISSUE THREAD

**Issue by thedarkness000** [kz26/dottorrent-gui#16]
In dottorrent-gui 1.3.4, clicking _Paste from clipboard_ does not work if the path on the clipboard is surrounded in double quotes.

For example, in Windows 8.1 and above, clicking _Copy path_ on the below file results in `"N:\Downloads\GoldenEye_Source_v5.0_full.exe"` being on the clipboard.
![copy path](https://i.imgur.com/sUJWraZ.png)

If I then click _Paste from clipboard_ in dottorrent-gui, nothing is populated in the input path field.  Removing the double quotes from around the path on the clipboard causes _Paste from clipboard_ to work as expected.

Can you update dottorrent-gui to support pasting double-quoted paths from the clipboard?  Thanks!

**Comment by kz26** [comment]
Thanks for the bug report. I'll try to have this fixed in the next release.

**Comment by kz26** [comment]
Fixed in 1.3.5.
