### ISSUE TITLE
Failed to execute script pyi_rth_qt5plugins

### ISSUE THREAD

**Issue by Burfiboy** [kz26/dottorrent-gui#17]
when i clicked the  application it is showing like "Failed to execute script pyi_rth_qt5plugins"

**Comment by kz26** [comment]
Hmm, can't seem to reproduce this. What is your OS?

**Comment by Burfiboy** [comment]
windows server 2012 R2

**Comment by mteamwhy** [comment]
hi
i got same problem,
i have two computer use win7
computer A can work and don't install any python program
computer B can't work and have install python

but computer B can use ver1.2.2 to work

any change after 1.2.2?

**Comment by Burfiboy** [comment]
fixed now by installing Visual C++ Redistributable for Visual Studio 2015

**Comment by kz26** [comment]
Thanks for the update. I'll add this to the README.
