### ISSUE TITLE
save dottorrent-gui.ini in program's folder instead of AppData

### ISSUE THREAD

**Issue by AdKiller** [kz26/dottorrent-gui#18]
option to to save dottorrent-gui.ini and any registry settings in program's folder instead of AppData would be great.
Thank you

**Comment by vatterspun** [comment]
I think AdKiller is asking for this because it would make the program portable, i.e. capable of being run from a USB or cloud drive without re-entering all your settings everytime.

**Comment by kz26** [comment]
Thanks for the update. I'll see if I can implement this in a future release.

**Comment by kz26** [comment]
This has been implemented in version 1.3.6 (see the readme for instructions). I currently do not have access to my main workstation, so unfortunately a new Windows x64 build might be delayed for a few weeks.

**Comment by vatterspun** [comment]
> This has been implemented in version 1.3.6 (see the readme for instructions). 

Great news, thanks.

**Comment by kz26** [comment]
Windows x64 build now available. https://github.com/kz26/dottorrent-gui/releases/tag/v1.3.6
