### ISSUE TITLE
[bug] selecting a individual file with batch checked = crash

### ISSUE THREAD

**Issue by mer2329** [kz26/dottorrent-gui#20]
issue: if you try and make a torrent with using "file mode" after enabling "directory>batch mode", the app will crash

to replicate:
optional) click the reset button.
1) change to "directory mode" and check batch mode.
2) switch to "file mode" and input any file
3) other settings dont matter.
4) click create, i saved the torrent file to the desktop

my setup: 
1) im using windows 10 pro 64-bit
1) i am using 1.3.6 i had initially installed a old version to program files, using nirsoft's zip installer. and i simply over write my installed version with each update.
2) i also tried the above with a new extraction to desktop as well as D drive
3) i also put a random video in the c drive to try.

because this is my first bug report i dont know what bug reports you need or how to get them.

**Comment by kz26** [comment]
Thanks for the bug report. I've managed to replicate this and will have this fixed in the next release.

**Comment by kz26** [comment]
Fixed in 1.3.7.

**Comment by mer2329** [comment]
Thanks for the awesome software. As well as the quick fix. 
I love the support for the source field.

I recommend this software to any user that will listen on the private trackers i use.

**Comment by kz26** [comment]
You're welcome, and good to hear!
