### ISSUE TITLE
Explanation of exclusions?

### ISSUE THREAD

**Issue by dragons4life** [kz26/dottorrent-gui#22]
Sometimes when adding multiple lines it just doesn't seem to work at all.

for example:
Folder>Files>
Grunge Texture 1 trough Grunge Texture v40 (mixed as .rar .zip)
Grunge Texture 41(help).rar
Grunge Texture 42_8000p.zip
Grunge Texture 42_4000p.zip
Grunge Texture 42_1000p.zip
Grunge Texture 43 (help).7z
Grunge Texture 44 (help).rar

Let's say I want to only add these files " Grunge Texture 1 trough Grunge Texture v40 (mixed as .rar .zip) "
I will add these to the exception box like this wouldn't I?
Grunge Texture 41(help).rar
Grunge Texture 42_8000p.zip
Grunge Texture 42_4000p.zip
Grunge Texture 42_1000p.zip
Grunge Texture 43 (help).7z
Grunge Texture 44 (help).rar
or
Grunge Texture 41(help)
Grunge Texture 42_8000p
Grunge Texture 42_4000p
Grunge Texture 42_1000p
Grunge Texture 43 (help)
Grunge Texture 44 (help)

Thing is that for some reason they still get added when creating the torrent.

**Comment by kz26** [comment]
Hi, are those files found at the root of the input directory, or are they in subdirectories?

**Comment by dragons4life** [comment]
In the main folder, no sub directories at all though if some of those files where in the sub-directories it still wouldn't work.

**Comment by kz26** [comment]
OK, thanks. I'll investigate this and get back to you.

**Comment by kz26** [comment]
I created some dummy files in a directory with the same filenames as you mentioned and fed it to dottorrent-gui 1.3.9 and was unable to reproduce the issue you're describing. What OS and version of dottorrent-gui are you using?

**Comment by dragons4life** [comment]
Latest & Windows 10
https://9.lithi.io/WhLsY3w.mp4

**Comment by kz26** [comment]
Ah, that makes more sense. Because dottorrent uses the fnmatch library, straight brackets are considered special characters: https://docs.python.org/2/library/fnmatch.html

In your particular example, doing *.srt might be easier, or if you need to use full filenames you'll have to escape each bracket like so: [[] or []]

**Comment by dragons4life** [comment]
Great.Stuff[UTR] > Great.Stuff[[]UTR[]]
Is the correct way? seemed to have worked thanks, I'll report here if It happens with non [ ] filenames, if it ever happens again.

Thanks for helping me out.

**Comment by kz26** [comment]
Yep, that looks correct. Glad you got it figured out, and thanks for using my software.

**Comment by Shelmor** [comment]
I realize that this is kinda late but still. File exclusion doesn't work for me no matter what I try. I may be stupid but at least I'll get some explanation on what I'm doing wrong (IF I'm doing this wrong). Here's a video of the behavioir I get: https://lithi.io/file/d5f2.mp4

**Comment by kz26** [comment]
Hi Shelmor, it wasn't clear from your video what exactly isn't working. Are the files not being excluded in the generated torrent file?

**Comment by Shelmor** [comment]
> 
> 
> Hi Shelmor, it wasn't clear from your video what exactly isn't working. Are the files not being excluded in the generated torrent file?

My bad, the generated torrent file is fine but the number of files at the bottom of the window is what confused me. I thought it showed the amount of files that are going to be added applying the exclusion, turned out it doesn't :)
