### ISSUE TITLE
Piece size defaults to auto in batch mode

### ISSUE THREAD

**Issue by stringybird** [kz26/dottorrent-gui#24]
If possible, it would be perfect if we could choose piece size regardless if it's batch or not.

**Comment by kz26** [comment]
The reason why I decided not to allow this is because fixed piece size doesn't work so well when the source content varies greatly in size. The other option would be to introduce additional GUI steps to set piece sizes individually for each torrent to be created, but in my opinion that's unnecessarily complicated. On the other hand, auto piece sizing allows each torrent to have a sensible piece count.

If you can come up with a convincing technical argument in favor of allowing manual/fixed piece sizes, I might consider implementing it.

**Comment by kdantas** [comment]
Hi kz26, are you ok? First, nice job with dottorrent-gui. But I have the same question of @stringybird. My convincing technical argument in favor of allowing manual/fixed piece sizes is very simple ... I need to create several .torrents from the same file with different piece size to do cross-seeding on various trackers. So, If I can't choose different piece size of the same file, then it is impossible to seed the same file on multiple trackers. I hope you can consider implementing this change. Thank you so much.

**Comment by kdantas** [comment]
> The reason why I decided not to allow this is because fixed piece size doesn't work so well when the source content varies greatly in size. The other option would be to introduce additional GUI steps to set piece sizes individually for each torrent to be created, but in my opinion that's unnecessarily complicated. On the other hand, auto piece sizing allows each torrent to have a sensible piece count.
> 
> If you can come up with a convincing technical argument in favor of allowing manual/fixed piece sizes, I might consider implementing it.

Hi kz26, are you ok? First, nice job with dottorrent-gui. But I have the same question of @stringybird. My convincing technical argument in favor of allowing manual/fixed piece sizes is very simple ... I need to create several .torrents from the same file with different piece size to do cross-seeding on various trackers. So, If I can't choose different piece size of the same file, then it is impossible to seed the same file on multiple trackers. I hope you can consider implementing this change. Thank you so much.

**Comment by kz26** [comment]
Fair enough, I can consider allowing manual piece sizes for batch mode in a future release. Alternatively, setting a unique source string should also result in a unique torrent for each tracker.

**Comment by kdantas** [comment]
> Fair enough, I can consider allowing manual piece sizes for batch mode in a future release. Alternatively, setting a unique source string should also result in a unique torrent for each tracker.

Hi @kz26, thanks for the quick response. Really setting a unique source string, we have a new hash code. This is an excellent tip for cross-seeding. Even then, would you have a release date of the new version with this manual change of the piece size in batch mode?

**Comment by mrpops2ko** [comment]
Please keep it as Auto. As you mentioned a modification of the source string is how you should cross seed, not creating torrents with millions of pieces or 10 pieces.

**Comment by kz26** [comment]
Due to the points made in favor of using unique source strings to enable cross-seeding, I've decided not to implement a manual piece size for batch mode at this time. The Auto mode as implemented should be sufficient to pick the best piece size in virtually all cases.
