### ISSUE TITLE
Missing dependency "humanfriendly"

### ISSUE THREAD

**Issue by markasoftware** [kz26/dottorrent-gui#25]
I got an error the first time I tried to run dottorrent-gui because I was missing the humanfriendly module. I manually installed it and all is well! However, it should be listed as a dependency so that `pip` automatically deals with this in the future.

**Comment by Shinra99** [comment]
Same here. I had to run `pip3 install humanfriendly`

**Comment by kz26** [comment]
Should be fixed in 1.3.10 which is now live. Thanks for the report.
