### ISSUE TITLE
Suggestion: Ability to paste path in box next to "Browse"

### ISSUE THREAD

**Issue by xomniversex** [kz26/dottorrent-gui#6]
Suggestion: Allow users to paste the path in the textbox instead of having to click "Browse" and browsing to it.

Use case: I often have the folder I want to compute and create a .torrent for already on my clipboard and in my workflow it is faster to just paste the path and then create the torrent file than it is to browse and then navigate to the folder in question.

Thank you.

**Comment by kz26** [comment]
Implemented in version 1.3.0/1.3.1.
