### ISSUE TITLE
Ability to make "piece size" larger than 4 MiB

### ISSUE THREAD

**Issue by the-researcher** [kz26/dottorrent-gui#7]
qBittorrent allows for the creation of torrents with piece sizes as large as 16 MiB, as well as other torrent clients.

I know that larger piece sizes may not be efficient, as there is the potential for greater error on a per-piece basis. However, allowing piece sizes for larger torrent filesets (50GB+) would be greatly appreciated, as it reduces the total size of the torrent file in question.

Not urgent, but it would be helpful.

Thanks!

**Comment by tn5421** [comment]
I second this request.

**Comment by scdemanett** [comment]
I third this request, at least 16 MiB but I would even like up to 32 MiB.

**Comment by kz26** [comment]
Implemented in version 1.3.0/1.3.1. Max piece size is now 64MB.
