### ISSUE TITLE
Suggestion: Add ability to include templates for files to skip

### ISSUE THREAD

**Issue by pastiche9761** [kz26/dottorrent-gui#9]
utorrent has the ability to create a delimited (|) template of files that will be skipped in the directory when the torrent is created. Could this be implemented?

From help file:
The Skip Files field allows you to skip files using specific filters. This field only gets activated if you use the "Add directory" button. Wildcards can be used to specify multiple files. 

In several places in µTorrent, wildcards can be used in place of normal characters in order to specify a pattern of characters that µTorrent should use to match whatever it needs. The following may be used in those situations:

* (asterisk) to match any text of any length 
? (question mark) to match any single character 
| (vertical pipe) is an "or" conditional 
Example: *File?A*|File?B* matches any file that contains File?A anywhere in the filename (where ? is any single character, such as a space or an underscore), or any file that begins with File?B in its filename (again, where ? is any single character).

**Comment by kz26** [comment]
Yes, file exclusion support is planned for the future. The dottorrent library would need to be updated as well.

**Comment by nyakze** [comment]
I second this. Since I migrated from uTorrent to qBt, I have to start up uTorrent again to make a torrent when I need to exclude certain filetypes from a folder.

**Comment by fecchan** [comment]
Since the dottorrent backend already [supported this](https://github.com/kz26/dottorrent/commit/fdb07db51c89c509deb11ef44decf6979aeb7302), I think it's just a matter of time until this gets implemented. Looking forward to it!

**Comment by kz26** [comment]
Yep, I plan to get this into the next release when I have a chance...unless of course someone beats me to it with a PR!

**Comment by kz26** [comment]
Implemented in version 1.3.0/1.3.1.
